# Generated by Django 5.2.8 on 2026-03-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0008_remove_ppryillikbajarildiimage_bajarildi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arizayuborish',
            name='status',
            field=models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi'), ('Bajarilmoqda', 'Bajarilmoqda'), ('jarayonda', 'Jarayonda')], default='jarayonda', max_length=20),
        ),
    ]
