# Generated by Django 5.2.8 on 2026-03-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0009_alter_arizayuborish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arizayuborish',
            name='status',
            field=models.CharField(choices=[('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi'), ('qabul qilindi', 'Qabul qilindi'), ('jarayonda', 'Jarayonda')], default='jarayonda', max_length=20),
        ),
    ]
