# Generated by Django 5.2.8 on 2026-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0010_alter_arizayuborish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arizayuborish',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('bajarilmoqda', 'Bajarilmoqda'), ('tasdiqlashga', 'Tasdiqlashga'), ('rad_etildi', 'Rad etildi'), ('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi')], default='jarayonda', max_length=20),
        ),
    ]
