# Generated by Django 5.2.8 on 2026-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0012_alter_kelganarizalar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arizayuborish',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('bajarilmoqda', 'Bajarilmoqda'), ('tasdiqlanmoqda', 'Tasdiqlanmoqda'), ('rad_etildi', 'Rad etildi'), ('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi')], default='jarayonda', max_length=20),
        ),
        migrations.AlterField(
            model_name='kelganarizalar',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('bajarilmoqda', 'Bajarilmoqda'), ('tasdiqlanmoqda', 'Tasdiqlanmoqda'), ('rad_etildi', 'Rad etildi'), ('bajarilgan', 'Bajarilgan'), ('qaytarildi', 'Qaytarildi')], max_length=20),
        ),
    ]
