# Generated by Django 5.2.8 on 2026-03-10 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0013_alter_arizayuborish_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XaridAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Ariza mazmuni')),
                ('fayl', models.FileField(upload_to='xarid_arizalari/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yuborildi', 'Yuborildi'), ('maqullandi', "Ma'qullandi"), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='yuborildi', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tuzilmalar', models.ManyToManyField(related_name='xarid_arizalari', to='ppr.tarkibiytuzilma')),
            ],
        ),
        migrations.CreateModel(
            name='XaridStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('maqullandi', "Ma'qullandi"), ('rad_etildi', 'Rad etildi')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('tuzilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppr.tarkibiytuzilma')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xarid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steplar', to='ppr.xaridariza')),
            ],
            options={
                'unique_together': {('xarid', 'tuzilma')},
            },
        ),
    ]
