# Generated by Django 5.2.8 on 2026-03-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0014_xaridariza_xaridstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xaridariza',
            name='status',
            field=models.CharField(choices=[('yuborildi', 'Yuborildi'), ('kelishildi', 'Kelishildi'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='yuborildi', max_length=20),
        ),
        migrations.AlterField(
            model_name='xaridstep',
            name='status',
            field=models.CharField(choices=[('kelishildi', 'Kelishildi'), ('rad_etildi', 'Rad etildi')], max_length=20),
        ),
    ]
