# Generated by Django 5.2.8 on 2026-03-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0015_alter_xaridariza_status_alter_xaridstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizayuborish',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yuborilgan_arizalar', to='ppr.bolim'),
        ),
    ]
