# Generated by Django 5.2.12 on 2026-03-11 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0016_arizayuborish_bolim'),
    ]

    operations = [
        migrations.AddField(
            model_name='xaridariza',
            name='kimdan_tomonidan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yuborilgan_xarid_arizalari', to=settings.AUTH_USER_MODEL),
        ),
    ]
