# Generated by Django 5.2.12 on 2026-03-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0017_xaridariza_kimdan_tomonidan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xaridariza',
            old_name='kimdan_tomonidan',
            new_name='kim_tomonidan',
        ),
    ]
