# Generated by Django 5.2.12 on 2026-03-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppr', '0018_rename_kimdan_tomonidan_xaridariza_kim_tomonidan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xaridariza',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to='xarid_arizalari/'),
        ),
    ]
